apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "secret-sync.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{include "secret-sync.labels" . | nindent 4}}
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch" ]
