apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "secret-sync.name" . }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secret-sync.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "refresh_interval": "{{ .Values.refreshInterval }}",
      "vault": {
        "address": "{{ .Values.vaultAddress }}"
      },
      "secrets": {{ .Values.vaultSecrets | toJson }}
    }

